"""Generate shell completions for every j-tool from its own argparse parser.

    uv run python scripts/gen_completions.py            # write completions/
    uv run python scripts/gen_completions.py --check    # fail if they are out of date (CI)

The flags come from the parsers themselves, so a new option is completable the moment it exists.
"""

from __future__ import annotations

import argparse
import importlib
import sys
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "completions"
sys.path.insert(0, str(ROOT / "src"))

from jevtools import TOOLS  # noqa: E402

MAX_CHOICES = 8  # more than this is a value to type, not a list to pick from


@dataclass(frozen=True)
class Tool:
    """What a shell needs to know about one command, read from its own parser."""

    flags: list[str]
    choices: dict[str, list[str]]  # flag -> the fixed values it accepts
    dirs: list[str]  # flags whose argument is a directory
    files: list[str]  # flags whose argument is a file
    subcommands: list[str]


def describe(tool: str) -> Tool:
    module = importlib.import_module(f"jevtools.{tool}")
    parser: argparse.ArgumentParser = module.parser()
    flags: list[str] = []
    choices: dict[str, list[str]] = {}
    dirs: list[str] = []
    files: list[str] = []
    subcommands: list[str] = []
    for action in parser._actions:
        values = [str(c) for c in action.choices] if action.choices else []
        if not action.option_strings:
            # A positional; a subparsers action carries the subcommand names.
            subcommands.extend(values)
            continue
        flags.extend(action.option_strings)
        if values and len(values) <= MAX_CHOICES:
            for flag in action.option_strings:
                choices[flag] = values
        # The metavar says what the argument is, so the shell can offer the right thing.
        elif action.metavar == "DIR":
            dirs.extend(action.option_strings)
        elif action.metavar == "FILE":
            files.extend(action.option_strings)
    return Tool(sorted(set(flags)), choices, sorted(set(dirs)), sorted(set(files)), subcommands)


def everything() -> dict[str, Tool]:
    return {tool: describe(tool) for tool in [*TOOLS, "jtools"]}


def merged(tools: dict[str, Tool]) -> tuple[dict[str, list[str]], list[str], list[str]]:
    """Value flags are shared across the tools, so one case arm each covers them all."""
    choices: dict[str, list[str]] = {}
    dirs: set[str] = set()
    files: set[str] = set()
    for t in tools.values():
        choices.update(t.choices)
        dirs.update(t.dirs)
        files.update(t.files)
    return choices, sorted(dirs), sorted(files)


def bash() -> str:
    tools = everything()
    choices, dirs, files = merged(tools)
    lines = [
        "# bash completion for j-tools. Generated by scripts/gen_completions.py; do not edit.",
        "# Install: source this file from ~/.bashrc, or drop it in /etc/bash_completion.d/.",
        "",
        "_jtools_complete() {",
        "    local cur prev tool flags subs",
        '    cur="${COMP_WORDS[COMP_CWORD]}"',
        '    prev="${COMP_WORDS[COMP_CWORD-1]}"',
        '    tool="${COMP_WORDS[0]##*/}"',
        '    subs=""',
        '    case "$tool" in',
    ]
    for tool, spec in tools.items():
        lines.append(f"    {tool})")
        lines.append(f'        flags="{" ".join(spec.flags)}"' + ("" if spec.subcommands else " ;;"))
        if spec.subcommands:
            lines.append(f'        subs="{" ".join(spec.subcommands)}" ;;')
    lines += ['    *) flags="" ;;', "    esac", '    case "$prev" in']
    for flag, values in sorted(choices.items()):
        if flag.startswith("--"):  # the short form shares the arm below
            aliases = "|".join([flag, *(f for f, v in choices.items() if v == values and f != flag)])
            lines.append(f'        {aliases}) COMPREPLY=( $(compgen -W "{" ".join(values)}" -- "$cur") ); return ;;')
    if dirs:
        lines.append(f'        {"|".join(dirs)}) COMPREPLY=( $(compgen -d -- "$cur") ); return ;;')
    if files:
        lines.append(f'        {"|".join(files)}) COMPREPLY=( $(compgen -f -- "$cur") ); return ;;')
    lines += [
        "    esac",
        '    if [[ "$cur" == -* ]]; then',
        '        COMPREPLY=( $(compgen -W "$flags" -- "$cur") )',
        '    elif [[ -n "$subs" && "$COMP_CWORD" -eq 1 ]]; then',
        '        COMPREPLY=( $(compgen -W "$subs" -- "$cur") )',
        "    else",
        '        COMPREPLY=( $(compgen -f -- "$cur") )',
        "    fi",
        "}",
        "",
        f"complete -F _jtools_complete {' '.join([*TOOLS, 'jtools'])}",
        "",
    ]
    return "\n".join(lines)


def zsh() -> str:
    tools = everything()
    choices, dirs, files = merged(tools)
    lines = [
        "#compdef " + " ".join([*TOOLS, "jtools"]),
        "# zsh completion for j-tools. Generated by scripts/gen_completions.py; do not edit.",
        "# Install: put this file as _jtools somewhere on your $fpath.",
        "",
        "_jtools() {",
        "  local -a flags subs",
        "  subs=()",
        '  case "${service}" in',
    ]
    for tool, spec in tools.items():
        subs = f" subs=({' '.join(spec.subcommands)});" if spec.subcommands else ""
        lines.append(f"    {tool}) flags=({' '.join(spec.flags)});{subs} ;;")
    lines += ["  esac", '  case "${words[CURRENT-1]}" in']
    for flag, values in sorted(choices.items()):
        if flag.startswith("--"):
            aliases = "|".join([flag, *(f for f, v in choices.items() if v == values and f != flag)])
            lines.append(f"    {aliases}) compadd {' '.join(values)}; return ;;")
    if dirs:
        lines.append(f"    {'|'.join(dirs)}) _files -/; return ;;")
    if files:
        lines.append(f"    {'|'.join(files)}) _files; return ;;")
    lines += [
        "  esac",
        '  if [[ "${words[CURRENT]}" == -* ]]; then',
        "    compadd -- ${flags[@]}",
        "  elif (( ${#subs} && CURRENT == 2 )); then",
        "    compadd -- ${subs[@]}",
        "  else",
        "    _files",
        "  fi",
        "}",
        "",
        '_jtools "$@"',
        "",
    ]
    return "\n".join(lines)


FILES = {"j-tools.bash": bash, "_jtools": zsh}


def main(check: bool) -> int:
    OUT.mkdir(exist_ok=True)
    stale = []
    for name, build in FILES.items():
        path = OUT / name
        body = build()
        if not path.exists() or path.read_text() != body:
            stale.append(name)
            if not check:
                path.write_text(body)
    if check and stale:
        print(f"out of date: {', '.join(stale)}; run scripts/gen_completions.py", file=sys.stderr)
        return 1
    print("unchanged" if not stale else "wrote " + ", ".join(stale), file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main("--check" in sys.argv))
