"""Generate shell completions for every j-tool from its own argparse parser.

    uv run python scripts/gen_completions.py            # write completions/
    uv run python scripts/gen_completions.py --check    # fail if they are out of date (CI)

The flags come from the parsers themselves, so a new option is completable the moment it exists.
"""

from __future__ import annotations

import argparse
import importlib
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "completions"
sys.path.insert(0, str(ROOT / "src"))

from jevtools import TOOLS  # noqa: E402

CHOICE_FLAGS = {"--api", "--color"}


def options(tool: str) -> tuple[list[str], dict[str, list[str]]]:
    """Every flag the tool accepts, and the fixed values of the flags that take a choice."""
    module = importlib.import_module(f"jevtools.{tool}")
    parser: argparse.ArgumentParser = module.parser()
    flags: list[str] = []
    choices: dict[str, list[str]] = {}
    for action in parser._actions:
        flags.extend(action.option_strings)
        if action.choices and action.option_strings:
            for flag in action.option_strings:
                if flag in CHOICE_FLAGS or len(action.choices) <= 8:
                    choices[flag] = [str(c) for c in action.choices]
    return sorted(set(flags)), choices


def bash() -> str:
    lines = [
        "# bash completion for j-tools. Generated by scripts/gen_completions.py; do not edit.",
        "# Install: source this file from ~/.bashrc, or drop it in /etc/bash_completion.d/.",
        "",
        "_jtools_complete() {",
        "    local cur prev tool flags",
        '    cur="${COMP_WORDS[COMP_CWORD]}"',
        '    prev="${COMP_WORDS[COMP_CWORD-1]}"',
        '    tool="${COMP_WORDS[0]##*/}"',
        '    case "$tool" in',
    ]
    for tool in [*TOOLS, "jtools"]:
        flags, choices = options(tool)
        lines.append(f"    {tool})")
        lines.append(f'        flags="{" ".join(flags)}" ;;')
        del choices
    lines += [
        '    *) flags="" ;;',
        "    esac",
        '    case "$prev" in',
        '        --api) COMPREPLY=( $(compgen -W "typesafe openrouter vercel gateway" -- "$cur") ); return ;;',
        '        --color) COMPREPLY=( $(compgen -W "auto always never" -- "$cur") ); return ;;',
        '        --out-dir|-o|--input|-i) COMPREPLY=( $(compgen -d -- "$cur") ); return ;;',
        "    esac",
        '    if [[ "$cur" == -* ]]; then',
        '        COMPREPLY=( $(compgen -W "$flags" -- "$cur") )',
        "    else",
        '        COMPREPLY=( $(compgen -f -- "$cur") )',
        "    fi",
        "}",
        "",
        f"complete -F _jtools_complete {' '.join([*TOOLS, 'jtools'])}",
        "",
    ]
    return "\n".join(lines)


def zsh() -> str:
    lines = [
        "#compdef " + " ".join([*TOOLS, "jtools"]),
        "# zsh completion for j-tools. Generated by scripts/gen_completions.py; do not edit.",
        "# Install: put this file as _jtools somewhere on your $fpath.",
        "",
        "_jtools() {",
        "  local -a flags",
        '  case "${service}" in',
    ]
    for tool in [*TOOLS, "jtools"]:
        flags, _ = options(tool)
        lines.append(f"    {tool}) flags=({' '.join(flags)}) ;;")
    lines += [
        "  esac",
        '  case "${words[CURRENT-1]}" in',
        "    --api) compadd typesafe openrouter vercel gateway; return ;;",
        "    --color) compadd auto always never; return ;;",
        "    --out-dir|-o|--input|-i) _files -/; return ;;",
        "  esac",
        '  if [[ "${words[CURRENT]}" == -* ]]; then',
        "    compadd -- ${flags[@]}",
        "  else",
        "    _files",
        "  fi",
        "}",
        "",
        '_jtools "$@"',
        "",
    ]
    return "\n".join(lines)


FILES = {"j-tools.bash": bash, "_jtools": zsh}


def main(check: bool) -> int:
    OUT.mkdir(exist_ok=True)
    stale = []
    for name, build in FILES.items():
        path = OUT / name
        body = build()
        if not path.exists() or path.read_text() != body:
            stale.append(name)
            if not check:
                path.write_text(body)
    if check and stale:
        print(f"out of date: {', '.join(stale)}; run scripts/gen_completions.py", file=sys.stderr)
        return 1
    print("unchanged" if not stale else "wrote " + ", ".join(stale), file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main("--check" in sys.argv))
