"""Write the measured numbers into README.md and docs/benchmarks.md.

    uv run python scripts/update_docs.py          # rewrite the generated blocks
    uv run python scripts/update_docs.py --check  # fail if they are out of date (CI)

Both files carry marker pairs::

    <!-- BEGIN <name> (generated by scripts/update_docs.py; do not edit) -->
    ...
    <!-- END <name> -->

Everything between them comes from ``bench/results/*.json``, so a number in the docs is always a
number some live run actually measured. Nothing else in either file is touched.

A figure that belongs mid-sentence gets an inline span instead::

    ... in about <!--num:latency_p50_round-->420 ms<!--/num--> for a thousandth of a cent.

Those are filled from the same results, in every Markdown file in the repository, so a paragraph
cannot quietly keep yesterday's number while the table above it moves.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from render_tables import accuracy_table, cost_table, latency_table, numbers, summary

ROOT = Path(__file__).resolve().parent.parent
BLOCKS = {
    ROOT / "README.md": {"bench-summary": summary},
    ROOT / "docs" / "benchmarks.md": {
        "bench-tables": lambda: "\n".join(b for b in (latency_table(), cost_table(), accuracy_table()) if b),
    },
}
SPAN = re.compile(r"<!--num:([a-z0-9_]+)-->(.*?)<!--/num-->", re.S)


def markdown_files() -> list[Path]:
    skip = {".venv", "node_modules", "dist", "out"}
    return [p for p in sorted(ROOT.rglob("*.md")) if not skip & set(p.parts)]


def fill_spans(text: str, values: dict[str, str], unknown: set[str]) -> str:
    def one(match: re.Match[str]) -> str:
        key = match.group(1)
        if key not in values:
            unknown.add(key)
            return match.group(0)
        return f"<!--num:{key}-->{values[key]}<!--/num-->"

    return SPAN.sub(one, text)


def begin(name: str) -> str:
    return f"<!-- BEGIN {name} (generated by scripts/update_docs.py; do not edit) -->"


def end(name: str) -> str:
    return f"<!-- END {name} -->"


def replace(text: str, name: str, body: str) -> str:
    start, stop = text.index(begin(name)), text.index(end(name))
    return text[: start + len(begin(name))] + "\n\n" + body.strip() + "\n\n" + text[stop:]


def main(check: bool) -> int:
    stale = []
    values = numbers()
    unknown: set[str] = set()
    for path in markdown_files():
        original = path.read_text()
        text = original
        for name, build in BLOCKS.get(path, {}).items():
            body = build()
            if not body.strip():
                body = "_No benchmark results recorded yet. Run `bench/` and `scripts/update_docs.py`._"
            text = replace(text, name, body)
        text = fill_spans(text, values, unknown)
        if text != original:
            stale.append(path.name)
            if not check:
                path.write_text(text)
    if unknown:
        print(f"unknown placeholder(s): {', '.join(sorted(unknown))}", file=sys.stderr)
        return 1
    if check and stale:
        print(f"out of date: {', '.join(stale)}; run scripts/update_docs.py", file=sys.stderr)
        return 1
    print(("unchanged" if not stale else "updated: " + ", ".join(stale)), file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main("--check" in sys.argv))
