# bash completion for j-tools. Generated by scripts/gen_completions.py; do not edit.
# Install: source this file from ~/.bashrc, or drop it in /etc/bash_completion.d/.

_jtools_complete() {
    local cur prev tool flags subs
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"
    tool="${COMP_WORDS[0]##*/}"
    subs=""
    case "$tool" in
    jgrep)
        flags="--all --api --budget --color --concurrency --context --count --csv --dry-run --exclude --field --files-with-matches --files-without-match --glob --help --hidden --invert-match --json --jsonl --line-number --max-chars --max-count --model --no-cache --no-filename --no-stats --para --prob --quiet --recursive --stats --strict --threshold --timeout --unordered --verbose --version --whole --with-filename -C -H -L -c -e -h -j -l -m -n -o -p -q -r -v" ;;
    jsort)
        flags="--api --asc --budget --color --concurrency --dry-run --help --json --levels --limit --max-chars --model --no-cache --no-stats --quiet --stats --strict --timeout --verbose --version --with-score -h -j -n -q -s -v" ;;
    jpick)
        flags="--api --budget --color --concurrency --dry-run --group --help --json --max-chars --model --no-cache --no-stats --quiet --stats --strict --timeout --top --verbose --version --why --with-score -h -j -q -s -v" ;;
    jgate)
        flags="--all --api --budget --color --concurrency --dry-run --each --fail-open --help --json --max-chars --model --no-cache --no-stats --print --quiet --stats --strict --threshold --timeout --verbose --version -P -h -j -p -q -v" ;;
    jwatch)
        flags="--all-lines --api --bell --budget --color --concurrency --cooldown --dry-run --exec --help --json --max --max-chars --model --no-cache --no-stats --quiet --stats --strict --threshold --timeout --verbose --version --with-score -h -j -p -q -s -v" ;;
    juniq)
        flags="--api --budget --color --concurrency --count --dry-run --help --json --max-chars --model --no-cache --no-stats --quiet --repeated --show-groups --stats --strict --threshold --timeout --unique --verbose --version --window -c -d -h -j -p -q -u -v -w" ;;
    jhead)
        flags="--api --budget --color --concurrency --dry-run --help --json --levels --max-chars --model --no-cache --no-stats --quiet --reorder --stats --strict --tail --timeout --verbose --version --with-score -h -j -q -s -v" ;;
    jtag)
        flags="--api --budget --color --concurrency --default --dry-run --help --json --label --labels --levels --max-chars --model --no-cache --no-stats --quiet --scale --score --sep --stats --strict --suffix --threshold --timeout --verbose --version --with-prob -h -j -p -q -v" ;;
    jroute)
        flags="--api --budget --color --concurrency --default --dry-run --ext --help --input --json --max-chars --model --no-cache --no-files --no-stats --out-dir --quiet --stats --stdout --strict --threshold --timeout --truncate --verbose --version -h -i -j -o -p -q -v" ;;
    jmatch)
        flags="--api --budget --color --concurrency --dry-run --format --group --help --json --max-chars --model --no-cache --no-stats --quiet --shortlist --stats --strict --threshold --timeout --unmatched --verbose --version -h -j -p -q -v" ;;
    jtools)
        flags="--help --version -h"
        subs="list doctor version" ;;
    *) flags="" ;;
    esac
    case "$prev" in
        --api) COMPREPLY=( $(compgen -W "typesafe openrouter vercel gateway" -- "$cur") ); return ;;
        --color) COMPREPLY=( $(compgen -W "auto always never" -- "$cur") ); return ;;
        --out-dir|-o) COMPREPLY=( $(compgen -d -- "$cur") ); return ;;
        --input|-i) COMPREPLY=( $(compgen -f -- "$cur") ); return ;;
    esac
    if [[ "$cur" == -* ]]; then
        COMPREPLY=( $(compgen -W "$flags" -- "$cur") )
    elif [[ -n "$subs" && "$COMP_CWORD" -eq 1 ]]; then
        COMPREPLY=( $(compgen -W "$subs" -- "$cur") )
    else
        COMPREPLY=( $(compgen -f -- "$cur") )
    fi
}

complete -F _jtools_complete jgrep jsort jpick jgate jwatch juniq jhead jtag jroute jmatch jtools
